### ISSUE TITLE
List applicable options in Hex documentation

### ISSUE THREAD

**Issue by schrockwell** [whitfin/cachex#115]
Currently in the documentation, many of the functions list an `options` argument but do not explain what the available options are.

If there is a common set of options available to all functions (e.g. `async`), then it could be listed in the moduledoc, with additional options being listed for each individual function.

It would be nice if the options were proper typespecs, but I'm not certain you can do that with keyword lists due to ordering.

**Comment by whitfin** [comment]
All options will be documented correctly as of #131; but most are already correct.

**Comment by schrockwell** [comment]
Thank you!!
