### ISSUE TITLE
Enable get the `write time` of the key-value

### ISSUE THREAD

**Issue by bingoabs** [whitfin/cachex#116]
I know the `Cachex.touch/3` can 

> Touches the last write time on a key

Then, how about provide a way to get the "write time" of certain key in the cache.

Or maybe I left some important message, please tip me, Thanks

**Comment by bingoabs** [comment]
Sorry, I found the `Cachex.inspect(:my_cache, { :record, "my_key" } )` can help my concern.
Hope it can performance well.

**Comment by whitfin** [comment]
@bingoabs yeah, you can just use the inspector as you demonstrated above. Let me know if you need anything further!
