### ISSUE TITLE
Add an `extract_key` option to the cache

### ISSUE THREAD

**Issue by Bharat311** [whitfin/cachex#122]
Hi, Thanks for the amazing work done on this. I have been using it in my project since sometime now.

I have a requirement where i want to cache some expensive computation and i was planning to use the `fallback` option.

**Example Scenario:**

I have an ecto Schema `Student` which embeds many `Exam`. Now i need to calculate the result for the student, which i can do given the student struct, however it is expensive. I want to cache this value.

Now, there are 2 ways to achieve this: 

Approach (1):
```elixir
Cachex.get(:marks, student_id, fallback: &get_student_from_db_and_calculate_grades\1)
```

Approach (2):
```elixir
Cachex.get(:marks, student, fallback: &calculate_grades\1)
```

Problem with (1) is that if there are 50 students and we need to cache marks for them, it will result in 50 queries to the db.

Approach (2) solves this problem as we can directly use the `student` struct within the fallback function. However, this will use the entire struct as the cache key, which is not ideal (it should instead have used student_id). 

Is there a good alternate way to achieve this? I thought about writing a wrapper for it in application, but that would be exactly similar to what the `fallback` already does.

One solution i can think of is - we can add an option to cache `extract_key` that takes a function, which helps in converting the given struct to a simple cache key.

I will be happy to work on the same and raise a PR for it.

**Comment by whitfin** [comment]
Hi @Bharat311,

Unless I'm missing something, you need to inline your fallback into the scope of your calls:

```elixir
Cachex.get(:marks, student_id, fallback: fn(student_id) ->
  # you can still use "student" in here
end))
```
