### ISSUE TITLE
Allow limit structures to include options for the policy implementation

### ISSUE THREAD

**Issue by steffenix** [whitfin/cachex#141]
I am trying to use cachex with:
```
%Cachex.Limit{
  limit: 2_000_000,
  policy: Cachex.Policy.LRW,
   reclaim: 0.5
}
```
I have put 10 millions entries
The data is deleted 50 per 50 and really slowly something like 50 every few seconds.
I a doing something wrong? Why is the 50 per 50 limit hardcoded?
Thanks

**Comment by whitfin** [comment]
Hi @steffenix,

The batch size is 50 because you want to avoid pulling back unnecessary records which aren't removed. Why do you have 10 million records in the cache, and why are they all expiring at the same time in the first place?

**Comment by whitfin** [comment]
I have turned this ticket into an enhancement to allow customization; but I feel that this is probably a use case that could be better solved with a different cache interaction.

**Comment by whitfin** [comment]
@steffenix I have opened a PR in #142 which will introduce a `batch_size` option in v3, to allow you to customize the size of each batch being removed. Feel free to reply with more information about your use case and we can still work on it if needed :)

**Comment by steffenix** [comment]
My use case is caching on average 200 to 300 values a tupple of two elements for the key and a boolean value for the value from a database returned value. The software runs on a docker containers with serval other services and I want to make sure the cache is not eating up the other services memory.

In my case because I am dealing with a large number of entries I think being abble to adjust the batch_size will really help.

Thanks

**Comment by whitfin** [comment]
@steffenix I'm a little lost; what is the use case with 10 million values? If your cache is only 200-300 values, do you even need to impose a limit?

**Comment by steffenix** [comment]
I have forgot to put per seconds.
