### ISSUE TITLE
Documentation/Readme on Statistics

### ISSUE THREAD

**Issue by mgwidmann** [whitfin/cachex#158]
I see a mention of "Statistics gathering" in the main README but no documentation anywhere about how to use it (other than turn it on).

A few questions I think the readme should discuss.
What statistics are tracked automatically?
Where or how do you gather the statistics?
Does it interface with other stats tools/ect?
Possible to track custom statistics?

**Comment by whitfin** [comment]
This is all likely covered in https://github.com/whitfin/cachex/issues/128. To answer your questions now though;

1. Basically everything.
2. Via a Hook.
3. Nope, nothing to do with any of them.
4. Sure, if you implement your own Hook.

I'll probably close this in favour of the linked issue, but feel free to comment further if you wish.
