### ISSUE TITLE
:missing breaking API change unmentioned

### ISSUE THREAD

**Issue by thurloat** [whitfin/cachex#175]
Just upgraded my app to Cachex 3.0.0, scanned the release notes and read the migration docs but none mentioned the change from `:missing, nil` responses to `:ok, nil` on `get/2` calls implemented here: https://github.com/whitfin/cachex/issues/151

Simple sweeping change to make in my application, but might help users with the upgrade if it were mentioned in the release and upgrade notes.

**Comment by whitfin** [comment]
Dropped a brief note in https://github.com/whitfin/cachex/commit/2c0b3dc240fed94978be534cfeceb6cc6b0c173e!

**Comment by stephenmoloney** [comment]
Just upgrading today, `{:ok, nil}` did throw me a bit.

I wonder if this sentence `If you need the same behaviour, you should avoid setting `nil` explicitly in your cache and put something else in instead` deserves a mention [here in the docs](https://github.com/whitfin/cachex/blob/master/lib/cachex.ex#L675-L687)
