### ISSUE TITLE
Recommended guidelines for testing caches

### ISSUE THREAD

**Issue by thiamsantos** [whitfin/cachex#179]
There is any recomended aproach to use cachex on my unit tests? How can I test if the cache was hitted? Should I use a hook?

**Comment by whitfin** [comment]
Yes, you can write a quick hook to inform you of whether your cache was used. You might want to check out the internal test cases; they use a hook which forwards all hook notifications back to the test process - from there you can determine what actions were taken by the cache.

**Comment by whitfin** [comment]
@thiamsantos do you need any further information here, or should this be closed?
