### ISSUE TITLE
Need to update description for start/3

### ISSUE THREAD

**Issue by jung-hunsoo** [whitfin/cachex#181]
I wrote an issue instead of PR to figure out what the writer's intended for. Two things need to be fixed.

1) Both description of start and start_link are same.

https://github.com/whitfin/cachex/blob/d2e39ac4a6a8e38c96d307414f55d38635e8891f/lib/cachex.ex#L108
https://github.com/whitfin/cachex/blob/d2e39ac4a6a8e38c96d307414f55d38635e8891f/lib/cachex.ex#L304

2) change of function identifier
- `start_link/3` to `start_link/2` and `start/3` to `start/2`.

**Comment by whitfin** [comment]
@jung-hunsoo thanks for the issue; this has been updated in master.

**Comment by jung-hunsoo** [comment]
Oh thanks.

@whitfin What's the difference between `get_and_update/4` and `fetch/3`?
