### ISSUE TITLE
Purge Hook Not Working?

### ISSUE THREAD

**Issue by mpope9** [whitfin/cachex#186]
Hello!  Love the cache!  I have ran into one problem.  I found this issue https://github.com/whitfin/cachex/issues/17 for purging hooks.  I've adjusted the example to run for the current version, and it appears that I can't reproduce the results.

```
iex(4)> import Cachex.Spec
Cachex.Spec
iex(5)>  defmodule MyModule.PostPurgeHook do
...(5)>    use Cachex.Hook
...(5)>
...(5)>    def handle_notify({ :purge, _opts }, state) do
...(5)>      IO.puts("Purge received!")
...(5)>      { :ok, state }
...(5)>    end
...(5)>
...(5)>    def handle_notify(_action, state) do
...(5)>      { :ok, state }
...(5)>    end
...(5)>  end
{:module, MyModule.PostPurgeHook,
 <<70, 79, 82, 49, 0, 0, 20, 48, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 2, 94,
   0, 0, 0, 61, 29, 69, 108, 105, 120, 105, 114, 46, 77, 121, 77, 111, 100, 117,
   108, 101, 46, 80, 111, 115, 116, 80, 117, ...>>, {:handle_notify, 2}}
iex(6)> Cachex.start_link(:my_cache, [hooks: [hook(module: MyModule.PostPurgeHook, state: self())], default_ttl: :timer.seconds(3), ttl_interval: :timer.seconds(5) ])
{:ok, #PID<0.453.0>}
iex(7)> Cachex.set(:my_cache, "key", "value")
{:ok, true}
```

Have I made a mistake?

**Comment by whitfin** [comment]
Hi @mpope9! 

Your hook syntax is slightly wrong; you're missing the middle argument of `results`:

```elixir
def handle_notify({ :purge, _opts }, result, state) do
```

Can you try that instead please?

**Comment by mpope9** [comment]
Ahh yes, thanks so much.

**Comment by mpope9** [comment]
Ahh, another question then, is there any way to get the records that are currently getting purged?

**Comment by mpope9** [comment]
As an example, I want to store some data in the cache to a database upon eviction.

**Comment by whitfin** [comment]
Unfortunately this isn’t possible as the amount of purged records can be extremely high - there’s no good way to communicate it through efficiently.

**Comment by Apelsinka223** [comment]
@mpope9 Hi, got same issue. I forked this repo and changed `purge` function to return 
`{:ok, <list_of_expired_records>}` so now I can catch records in hook https://github.com/LLCAEON/cachex_extended. You can use it with`{:cachex_extended, github: "LLCAEON/cachex_extended"}` and use cachex at the same time. Hope it will help :)

**Comment by Apelsinka223** [comment]
@whitfin maybe this logic can be added as optional in config to the `start_link`? That way it wouldn't be breaking change and anybody, who can accept low performance for one table, will be able use it?

**Comment by whitfin** [comment]
@Apelsinka223 It's not about performance, it's about feasibility. If you have a large cache of several thousand items (I have several projects with hundreds of thousands), this is not even possible - it would blow up your application.

It would be better to work out a way to structure a project without needing this; what exactly are your use cases @Apelsinka223 & @mpope9?

**Comment by Apelsinka223** [comment]
I store file paths by keys in cache and I need to delete files which paths purges from cache

**Comment by florinpatrascu** [comment]
@Apelsinka223 - we're too using Cachex for storing a lot of data in it, and from a consumer perspective, I support the concerns raised by @whitfin. But given the scenario you described, are you persisting the cache? If not, and the app is restarting, how do you delete the files, if their paths are lost; when the cache restarted? You could schedule their deletions using a queue manager, or similar?!

**Comment by Apelsinka223** [comment]
@florinpatrascu its stored in tmp directory, so its anyway would be deleted. I can't use scheduled delete, because of some files can be deleted before use when deletion would be run. Other way this monitoring process will be almost same: check time and delete expired and also check if cache for this path already deleted. I thought it would be easier to use cachex for this, no need to write same logic and synchonize it.
