### ISSUE TITLE
Links on hexdocs link to master instead of specific version tag

### ISSUE THREAD

**Issue by princemaple** [whitfin/cachex#188]
This could cause confusion when there unreleased change.

Docs should be published under specific versions.

https://hexdocs.pm/cachex/Cachex.html#put/4 links to https://github.com/whitfin/cachex/blob/master/lib/cachex.ex#L1021

https://hexdocs.pm/ecto/Ecto.Query.html#select/3 links to https://github.com/elixir-ecto/ecto/blob/v2.2.10/lib/ecto/query.ex#L774

**Comment by whitfin** [comment]
@princemaple I'm not sure what you mean; those docs are uploaded via `hex.publish`, so I'm assuming that this is a Hex issue rather than an issue here, right?

**Comment by princemaple** [comment]
I'm not exactly sure either. I'll ask around.
