### ISSUE TITLE
Is get_and_update an atomic operation ?

### ISSUE THREAD

**Issue by niahoo** [whitfin/cachex#190]
Or should I alaways use a transaction if I want to get the value, perfom complicated stuff and then set a new value ?

Thank you !

**Comment by whitfin** [comment]
Hi @niahoo!

There is an implicit transaction internally on the key you're working with, see here: https://github.com/whitfin/cachex/blob/1ed722ae71a9dcbd0c1ac34e687cc5dbbbbcb304/lib/cachex/actions/get_and_update.ex#L32.

**Comment by niahoo** [comment]
Thank you very much
