### ISSUE TITLE
fetch sometimes executes fallback unnecessarily

### ISSUE THREAD

**Issue by ivan** [whitfin/cachex#192]
Hi Isaac,

Thanks for publishing cachex, it looks great.

I was poking at `fetch` with a `fallback` where the fallback function would [`fetch` another key](https://github.com/ivan/trycachex/blob/1e1e6b3a482bcbee21d876dd93fd558eba509c76/lib/trycachex.ex#L47), and noticed that the fallback was called twice for that key, even though Cachex could have waited very briefly for the value to appear in the cache (because it was already fetched in parallel).  Is this a bug?

I have a repro case:

```
git clone https://github.com/ivan/trycachex
cd trycachex
mix deps.get
MIX_ENV=prod mix escript.build
./trycachex parallel
```

```
# ./trycachex parallel
get :thing1
get :thing2
get :superthing
get :subthing
waiting for subthing
get :subthing
waiting for subthing
%{
  subthing: "subthing!",
  superthing: "superthing with subthing!!",
  thing1: "thing one!",
  thing2: nil
}
```

(Note two `"waiting for subthing"`)

Thanks,

Ivan

**Comment by ivan** [comment]
I believe there is a race, because changing the sleep duration in

```elixir
      :superthing -> Process.sleep(500); {:commit, "superthing with #{get(:subthing)}!"}
```

to either `400` or `600` results in `fallback(:subthing)` being called just once.

**Comment by ivan** [comment]
Yeah, that is what I expected.

I don't yet know the nature of the race (maybe the `send(parent, { :notify, key, result }` is still in flight when the task list is emptied?).  The sleep durations do need to match nearly to the millisecond for the race to happen.

Thanks, I'll see if I can investigate further.

**Comment by whitfin** [comment]
@ivan If you look at the source of the Courier service, if the `send` has not happened, any calls for a key will just be buffered internally if there are already in-flight requests.

If the `send` has happened, it should insert the key to the cache and then flush the list of keys in the buffer (and resolve them all at the same time). All of the dispatch is sequential so it should be almost impossible to get a race internally, unless it's with the actual message passing.

To answer your question; it can't still be in flight because that `send` call is what triggers the task list being emptied.

**Comment by ivan** [comment]
Ah, thanks for the explanation, I'll dig further then.

**Comment by ivan** [comment]
I thought there might be some kind of race with ets itself, but I turned off read and write concurrency on all the tables and still saw the same problem.

After thinking about this code in `actions/fetch.ex`, though:

```elixir
  defaction fetch(cache() = cache, key, fallback, options) do
    with { :ok, nil } <- Get.execute(cache, key, const(:notify_false)) do
      Courier.dispatch(cache, key, generate_task(cache, fallback, key))
    end
  end
```

it looks like this sequence of events can happens:

1. `Get.execute` returns `{ :ok, nil }`
2. the Courier process runs its `handle_info({ :notify, ... }` from an existing fallback task 
3. `Courier.dispatch(...)` puts `{ :dispatch, key, task }` into the Courier mailbox
4. Courier assumes the key isn't in the cache and does an unnecessary call to the fallback function

That is, because the ets lookup and the Courier are asynchronously decoupled, the Courier might be given a new `:dispatch` for a key when it's still doing the `handle_info({ :notify, ... }` for the same key.

**Comment by whitfin** [comment]
@ivan that actually makes sense (disregard first comment on the PR). Nice find!
