### ISSUE TITLE
Issue with Stripped Release Build

### ISSUE THREAD

**Issue by michaelkschmidt** [whitfin/cachex#205]
When trying to use Cachex in a release build with debug info stripped, it always returns `:invalid_hook`

```
iex(release_test@127.0.0.1)1> Cachex.start_link :some_cache, limit: 7
{:error, :invalid_hook}
```

Here is a repo with a full setup:
https://github.com/michaelkschmidt/release_test

Note the custom plugin as Distillery does not currently strip debug information correctly:
https://github.com/bitwalker/distillery/pull/591

**Comment by michaelkschmidt** [comment]
I managed to track this down to a missing 'Attr' chunk.  The fix for distillery is here:
https://github.com/mobileoverlord/distillery/pull/1

**Comment by OvermindDL1** [comment]
A workaround would be if Cachex just no-ops that behavious/attributes check on release builds (say via a compile-time configuration option) so stripping wouldn't matter then as it would be tested in dev/test anyway.

**Comment by michaelkschmidt** [comment]
@OvermindDL1 that would work in this case, but I still think the upstream `strip` should be fixed as other modules may depend that functionality too

**Comment by tsloughter** [comment]
I just became aware of this issue and the change to OTP. As a maintainer of rebar3/relx and someone who wants Elixir applications to be available to Erlang users with as little friction as possible this concerned me. Stripping is very common and even if relx supported this new form of stripping it is certainly going to be confusing and hard to find what is going wrong.

Why does it have calls to `module.__info__(:attributes)`?

**Comment by whitfin** [comment]
@tsloughter it doesn't _have_ to. It's basically detecting (at startup only) if the provided atom is a valid module and can have functions invoked on it. I could tweak to check if the atom name starts with `Elixir.` (as mentioned above), but considering it randomly broke stuff I felt fine with the issue going upstream. It's essentially just protection against giving me a bad module at startup and not finding out until your code paths are actually hit.

Regardless of what I do here though, I think you'd be surprised about how often you see code like that - I'd imagine it's quite common in the voodoo DSL libraries that are kicking around.

**Comment by tsloughter** [comment]
Why check if it begins with `Elixir.`? Does this only work with Elixir modules and not Erlang/lfe/etc?

Is it checking if it is a module with some specific attributes or really just if it is a module at all? I usually see that done in Erlang with, `try Module:module_info() catch ... handle it not existing ... end`.

**Comment by michaelkschmidt** [comment]
@tsloughter the reason I pushed this upstream is that `module.__info__(:attributes)` is broken by stripping, which is surprising.  This kind of error is extremely hard to figure out

**Comment by whitfin** [comment]
@tsloughter not a clue if it works with Erlang, I didn't build it with Erlang in mind at the time - if it does, it's coincidental (although against making it compatible).

If you mean that I can just switch to `Module:module_info()` I'm happy to :) the current literally is just checking that it's valid module. One other place would be https://github.com/whitfin/cachex/blob/b3dada8e4aa07710ef221da435eac01ad807fc9e/lib/cachex/spec/validator.ex#L121-L122 which checks for exposed functions.

**Comment by michaelkschmidt** [comment]
@whitfin I think the `:functions` checks are ok, its just the `:attributes` one that will fail.  What if we log if the check fails instead of hard crashing?  If it is set to `debug` it will be easy to compile out
