### ISSUE TITLE
Prevent cache warming if phx.server in not executed

### ISSUE THREAD

**Issue by ribanez7** [whitfin/cachex#214]
Hi,

Is there any way to prevent cache warming when the server is not booting? I have a warmer that performs a query on application boot. That works perfectly, but almost every time I execute a mix task the warmer is also fired, so my attemt to solve this was to create a conditional:

```elixir
if Application.get_env(:phoenix, :serve_endpoints) do
      Map.put(
        caches_map,
        :counters,
        {[warmers: [warmer(module: MyWarmer)]], [id: :blabla]}
      )
    else
# ...
```

But this is not working on deploys because there are still some other tasks, appart from phx.server setting the serve_endpoints value.

Do you know any approach to do so?

Many thanks,

Rubén

**Comment by whitfin** [comment]
@ribanez7 doing what you're doing makes sense. Perhaps you can use the warmers based on the `Mix.env` configuration?

**Comment by whitfin** [comment]
Going to close this as there has been no response, if you need anything else feel free to respond!
