### ISSUE TITLE
Bug returning a tuple from Cachex.execute/3

### ISSUE THREAD

**Issue by axelson** [whitfin/cachex#216]
`Cachex.execute/3` typespec is: `execute(cache(), function(), Keyword.t()) :: {status(), any()}`

But it appears that `execute/3` always return the result of the function directly:
```
iex(22)> Cachex.execute(:hobnob_cachex, fn _worker -> {"hi", "there"} end)
{"hi", "there"}
```

Instead I would expect a return like this:
```
iex(22)> Cachex.execute(:hobnob_cachex, fn _worker -> {"hi", "there"} end)
{:ok, {"hi", "there"}}
```

This doesn't seem to be a problem with the typespec because there is also a `execute!/3` version of the function.

**Comment by whitfin** [comment]
Actually, you're not wrong. There's no point having `execute!` because yes, it should return what you return from the function. Want to PR the change to the typespec?

**Comment by axelson** [comment]
Created #217 to address this
