### ISSUE TITLE
Node list polling/refresh?

### ISSUE THREAD

**Issue by bjunc** [whitfin/cachex#219]
Somewhat bringing back up #79, now that distributed cache is back (but without the Phoenix/Presence dep).

I think I am running into a timing issue, where the nodes are not yet connected, before Cachex starts up.  So each node is getting its own cache instance, even though they eventually do connect (eg. channels are connected).  I believe this is because I am using Peerage, which has a delayed config, as well as polls for nodes (eg. in a scaling cluster).

Any chance Cachex could occasionally poll for updates to `Node.list`, or expose a manual update?

What exactly happens as new nodes are added? How does Cachex know about them? Is the cache only distributed across the initially connected nodes when Cachex was started?

Thanks!

**Comment by whitfin** [comment]
The problem with polling is that adding/removing nodes isn't great for data that exists... if you have 5 nodes and "key1" hashes to node 1, you might add 5 more and then it hashes to node 6 (for example). This means that we'd have to do a large migration, which is not easy.

I'm not against it, it's just a bit over-complicated for where we're at. If someone has a good solution that's not going to launch us into crazy balancing attempts, I'm all for it!

**Comment by bjunc** [comment]
I ended up going in a different direction, which seems to be working well.  Interested to hear your thoughts.

We're currently using libcluster in GKE. Using pg2, each node broadcasts local cache changes to the other nodes (every node ends up with a copy of the cache). Initial boot-up (eg. k8s scaling) requests a cache export from the other nodes, then imports for local use. Here's an explanation (not my article):
https://stephenbussey.com/2019/01/29/distributed-in-memory-caching-in-elixir.html

This has a few downsides of course, but it's working well for us.  Could something like this be "built-in" to Cachex?

**Comment by whitfin** [comment]
@bjunc that sounds reasonable, and to be honest I don't know how we could do "better" in a world where data has to be guaranteed. I'm going to close this for now, seeing as you're unblocked (sorry about the late reply!), but I will think about ways we can handle this better in future. There must be something! :)

**Comment by bjunc** [comment]
@whitfin as a follow-up, I've used this approach in production since my post in June. It works pretty well. It essentially requires a wrapper around cachex, where functions like `put` will put to local cache first (and upon`{:ok, true}`), then broadcast out to other nodes via pg2 so they can update their local stores with the same value / options. I haven't really had any side-effects / unintended consequences that I can think of.

So this logic could essentially be a separate library, but I could see the benefit of baking this into Cachex as a first-class feature.

**Comment by whitfin** [comment]
@bjunc I'm curious if you built that as a hook, or just as a wrapper? It seems like something a Cachex hook would be good for - it would listen for `put` (etc) and then re-broadcast around. 

If it can be made into a hook, I'm much more for baking this in. I generally prefer the modular approach for this lib, where adding extra stuff is just enabling a hook rather than having to learn something completely new. It makes it nice and easy to turn things on and off.

**Comment by bjunc** [comment]
It wasn't a hook (I don't recall why hooks weren't used).  Looks a bit like this (roughly, but you get the idea):

``` elixir
def put(key, value, opts \\ []) do
  case Cachex.put(@cache_service_name, key, value, opts) do
    {:ok, true} ->
      update_remotes(key, value, opts)
      {:ok, true}

    rest ->
      rest
  end
end


defp update_remotes(cache_key, value, opts) do
  Task.start(fn ->
    on_remotes(fn pid ->
      send(pid, {:broadcast, @pg_name, {:put, cache_key, value, opts}})
    end)
  end)
end


defp on_remotes(func) do
  @pg_name
  |> :pg2.get_members()
  |> Kernel.--(:pg2.get_local_members(@pg_name))
  |> Enum.each(func)
end


def handle_info({:broadcast, @pg_name, {:put, cache_key, value, opts}}, state) do
  opts = Cachex.Spec.const(:notify_false) ++ opts
  Cachex.put(@cache_service_name, cache_key, value, opts)
  {:noreply, state}
end
```
