### ISSUE TITLE
Infinite timeout when using `Task.async` in fallback function

### ISSUE THREAD

**Issue by alex88** [whitfin/cachex#220]
We're currently using `fetch/3` to cache a phoenix controller action, the cache code is like this:

```
fallback_fn = fn ->
  {:commit, realtime_data(params)}
end

result = case Cachex.fetch(:cache, cache_key, fallback_fn) do
  {:commit, result} ->
    Cachex.expire(:cache, cache_key, :timer.seconds(60))
    result

  {:ok, result} ->
    if Cachex.exists?(:cache, cache_key) == {:ok, true} and Cachex.ttl(:cache, cache_key) == {:ok, nil} do
      Cachex.expire(:cache, cache_key, :timer.seconds(60))
    end

    result

  {:error, error} ->
    Cachex.del(:cache, cache_key)
    raise error
end
```

inside our `realtime_data(params)` function we use `Task.async` and `Task.await`, the problem we're experiencing is that if that process crashes, the process running `realtime_data(params)` crashes too (because they're linked). Cachex then seems to never return and all future `fetch` calls will probably wait for the first call that is still pending.
Other than not using `Task.async` in our fallback code, is there a way to have Cachex handle this and at least throw an error instead of blocking all future calls?

**Comment by alex88** [comment]
This can be easily tested with this example:

```
defmodule CachexTest do
  def bad_function() do
    task = Task.async(fn () ->
      :timer.sleep(1000)
      raise "Error"
    end)
    Task.await(task)
  end

  def test do
    Cachex.start_link(:my_cache, [])

    fallback_fn = fn ->
      {:commit, bad_function()}
    end
    Cachex.fetch!(:my_cache, "foo", fallback_fn)
  end
end
```

```
iex(2)> CachexTest.test()

11:50:06.796 [error] Task #PID<0.235.0> started from #PID<0.234.0> terminating
** (RuntimeError) Error
    (cachex_test) lib/cachex_test.ex:5: anonymous fn/0 in CachexTest.bad_function/0
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<0.61446507/0 in CachexTest.bad_function/0>
    Args: []
```

as you can see even if the process crashes there is no return value nor a generated exception

**Comment by alex88** [comment]
The problem with the `nolink` which is easier to handle is that the courier dispatch doesn't catch errors, so the parent probably sits there waiting for a send from it that never arrives, adding

```
result =
try do
  task.()
rescue
  e ->
    { :error, Exception.message(e) }
catch
  e ->
    { :error, Exception.message(e) }
  e, b ->
    { :error, b }
end
```

seems to be working as it actually throws an exception

**Comment by whitfin** [comment]
@alex88 so... I'm a bit lost on this. What exactly should Cachex be doing, in your opinion?

**Comment by alex88** [comment]
@whitfin handle also exit errors, otherwise the next time `Cachex.fetch` is called, it just sits there and never moves forward

**Comment by whitfin** [comment]
But that's the intended behaviour; you can simply handle that error in your code and there's no issue, no?

**Comment by alex88** [comment]
Oh sure, if it's intended to hang forever because the previous call thrown an exception then I'll close the issue and handle it in my code
