### ISSUE TITLE
A Weak Distribute Cache

### ISSUE THREAD

**Issue by falood** [whitfin/cachex#222]
Hi @whitfin , 
Thanks for the awesome library.
In my use case, I hold all keys on local node with it's own value and ttl, may be the same or different from other nodes, I think I'll have a better performance than the distribute cache.
but when the system start, I need to initialize cache to avoid too many cache missing, the data can be synced from any active node.

I checked the codes and docs, I know how to do this myself with some low level interface(read ets directly), do you have any suggestion for this feature?

Thanks

**Comment by whitfin** [comment]
Hi @falood!

I think the best way to do this is to just RPC another node at startup and call the `export/2` function which is in the current master branch. You can then use the `import/2` function on the local node to import all of the entries into the local node. This wouldn't keep them in sync, but it would have a fairly warm cache at startup to make sure that you have some in memory. 

If you try it out and it works, I can publish the latest master as a v3.2.0 for you!

**Comment by falood** [comment]
thanks for your response.
currently I'm using a gen_server like this for cache warm, I also checked `export/2` and `import/1`, looks like the same logic, I'll give them a try.

```
# Supervisor Children
{CacheMonitor, [:cache1, :cache2]}

# Module
defmodule CacheMonitor do
  @moduledoc """
  Cache Monitor.
  """

  use GenServer

  def start_link(caches) do
    GenServer.start_link(__MODULE__, caches, name: __MODULE__)
  end

  def init(caches) do
    Enum.each(caches, &initialize/1)
    {:ok, nil}
  end

  def handle_call(:status, _from, state) do
    {:reply, :ok, state}
  end

  defp initialize(cache, retry \\ 3) do
    with {[_ |_] = replies, _} <- GenServer.multi_call(Node.list(), CacheMonitor, :status, 2000),
      {node_name, _} <- Enum.random(replies),
      exported <- :rpc.call(node_name, :ets, :tab2list, [cache]),
      true <- :ets.insert(cache, exported) do
      :ok
    else
      _ when retry > 0 -> initialize(cache, retry - 1)
      _ -> :error
    end
  end
end
```

**Comment by whitfin** [comment]
@falood did `export` and `import` work well for you?

**Comment by falood** [comment]
I haven't tried, will test it and let you know.
so, let's reopen this issue until we get the result.

I also have another question, it's related to this, I'm not sure should I open a new issue.
will servers call each other by default?
we have several servers in our cluster and each one have it's own table, but with the same name.
We got high cpu usage sometimes only on one server, and it goes to another one if we stop the spike one.

I'm not sure whether it's related to cachex, so I want to know the default cluster logic.

Thanks

**Comment by whitfin** [comment]
As long as you assign all nodes to the cache, the cache will use all nodes evenly.
