### ISSUE TITLE
Sliding expiration

### ISSUE THREAD

**Issue by wanton7** [whitfin/cachex#224]
I read the docs but could find any mention about sliding expiration. Is sliding expiration supported? 

I'm C# programmer by profession and as an example ASP.NET supports sliding expiration authentication cookies. It works like this, if you have expiration set to 20 minutes when half of that time is gone (10 minutes) and new request is made then expiration reset back to 20 minutes.

I would like to have something similar to that. So that keys that keep getting accessed would never expire.

**Comment by whitfin** [comment]
Yes, you can use `Cachex.refresh(:cache, "key")`. This will refresh the expiration exactly as you described above. 

If you want to make it "automatic", you can use a hook to refresh keys after they're read from.

**Comment by wanton7** [comment]
Thanks for the info!
