### ISSUE TITLE
Creating a cache with compression enabled?

### ISSUE THREAD

**Issue by woodyblah** [whitfin/cachex#226]
Hello,

Is there a way to create a cache that has the ets `:compressed` feature enabled?

I couldn't find a mention of it in the documentation, and this bit of code makes me think there isn't currently: https://github.com/whitfin/cachex/blob/b3dada8e4aa07710ef221da435eac01ad807fc9e/lib/cachex/spec.ex#L337-L342

I am happy to look at implementing this feature if there is not already a way to do this.

**Comment by whitfin** [comment]
There used to be, but it was removed a while ago. What is your use case that requires a compressed table?

In general compression slows the table, which is why it was removed. Caches interact with the table a lot, and to slow it down could be significant. I'm not particularly against adding it back as a new option, but would like to understand your reasoning why - and we would have to have benchmarks with/without for comparison.

**Comment by woodyblah** [comment]
For our use case we are caching large numbers of web pages (not gzipped from source, out of our control) for long periods of time as a sort of "fallback" cache, where we always try and fetch the fresh page from the origin as a first preference, and only serve from the cache in case of failure. There are a large number or variations, and we would like to keep the items for 6 or so, but this does lead to large amounts of memory being used very quickly. Compression would help us to increase the number of items we can keep in the cache, and as the page has already failed for whatever reason speed is no longer really our priority, serving the fallback slowly is better than nothing in our case. 

It would be interesting to do some benchmarks to see exactly how much slower it is, but unless it really is dramatic having more stuff in the fallback cache would serve us better than serving them quickly.

**Comment by OvermindDL1** [comment]
@woodyblah I'd probably opt for Cachex being a 'fast' cache for often requested things, but put things like that page cache in DETS or so instead, to keep them out of RAM until they are actually requested (I.E. have Cachex call things from DETS when the main page isn't working).

**Comment by woodyblah** [comment]
Yes I agree, I think for most cases people would want Cachex to be fast I think if it were to be added compression would be optional for sure, and if the performance really is hit badly then it would probably need added documentation/warnings not to use the compression option lightly. 

dets is something I'll look into, I'd be interested to check if a compressed ets is still faster than a dets for my use case, and to compare that as well with out current "fallback" cache which is being written to/fetched from from a remote store (S3). The reason I went with ETS to start with is because the servers we're using have plenty of unused RAM, but would have to pay to get more disk space. 

The only issue with using dets foresee is having to reimplement the TTL/item limit protocols/Janitor that are great features of Cachex for our dets tables.. Maybe there is already a Cachex like wrapper around dets that you know of?

**Comment by OvermindDL1** [comment]
Compressed ets is still faster than dets I'd not doubt (though benchmark!), but the thing about dets is that it keeps it out of ram entirely.

> The reason I went with ETS to start with is because the servers we're using have plenty of unused RAM, but would have to pay to get more disk space.

Lol, that's oddly backwards...  Maybe ETS with compressed would be better for your use-case?

> Maybe there is already a Cachex like wrapper around dets that you know of?

Hmm, not a bad idea, but it's not hard to make a janitor.  You might even look at using leveldb instead (there is both a pure-elixir library and a NIF library), as it will be a lot faster than dets, still file-based, and it is easier to janitor-run over it.  Wouldn't surprise me if something is made in Elixir already for TTL ejection of some filesystem thing though.

**Comment by whitfin** [comment]
> You might even look at using leveldb instead (there is both a pure-elixir library and a NIF library)

I would definitely back this option; it seems like a better model.

> Wouldn't surprise me if something is made in Elixir already for TTL ejection of some filesystem thing though.

If not, hm... :)

However, @woodyblah, I don't see why this shouldn't be a potential feature (regardless of your use case). I'll try and find some time to sit and benchmark differences, and see if it's something we should include. I worry that people will react as "Wow, less memory? Of course I want that enabled!", and then I start getting tickets about it being very slow.

**Comment by OvermindDL1** [comment]
> Of course I want that enabled!", and then I start getting tickets about it being very slow.

Could call the option `slow_compression` or something.  ^.^

**Comment by whitfin** [comment]
@woodyblah I have added the ability to turn this on via `:compressed` in https://github.com/whitfin/cachex/commit/cbfd7acbc4c1f4c59b0b4653ced49e5d2505dd0d. It will be available shortly in v3.2.0. 

I added a benchmarking option to try with/without compression. There's very little difference for the cases in the repository, but I imagine it's highly variable to your use case.
