### ISSUE TITLE
Advice: Invalidation Patterns?

### ISSUE THREAD

**Issue by coladarci** [whitfin/cachex#228]
Hello! Just playing w/ this library for the first time (after hearing many great things!) and I am very impressed w/ how easy it was to get up and and running.

Obviously one of the hardest parts of good caching is invalidation.. Sure, for simple cases, this is trivial; just invalidate the key. But for complex scenarios where you want to find all records that might need invalidating based on a change, this gets hard. 

We also use Fastly and they have a wonderful feature where you can attach tags to a given cached entry and then invalidate based on tag. This allows you to invalidate entire groups of records easily. For example, let's say you have a cache key of `person_1` who looks like: 

```
  %{
    id: 1,
    name: "Greg",
    company: %{
      id: 1,
      name: "Greg's Company"
    }
   }
```

You might tag this as [`person_1`, `company_1`] and then when company 1 has a change, I could just invalidate `company_1` and my person record automatically gets cleared. 

Given the above, do you have any advice on how you might approach this w/ Cachex? All I can think of is scanning the entire set of cached entries and look through them and make decisions, which is fine, but feels less elegant considering all the other niceties in this library.

Thanks!

PS - in writing this up, I s'pose a pattern could be to wrap the cached entry in a data structure that could have tags, and then you'd be scanning all entries for a given tag and invalidate those. Similar to the above, but easier to maintain? I'm fine w/ this solution, but am curious if there is a more obvious pattern I'm missing!

**Comment by OvermindDL1** [comment]
Huh, mapping a tag to a list of cache key's in the cache itself wouldn't be too hard.  Can be done manually but this sounds like it would be a cool PR for Cachex!

**Comment by coladarci** [comment]
Yeah, so theoretically, my desired flow might be 

```
res = Cachex.fetch(:my_cache, "person_1")
Cachex.tag(:my_cache, "person_1", "company_#{result.company.id}")
Cachex.expire_tag!(:my_cache, "company_1")
```

Where `tag/3` and `expire_tag!/2` would be the new functions.

**Comment by OvermindDL1** [comment]
Honestly I'd expect a PR to be able to pass a `tag: ...` option (of `term()` type) to the insertion handler, instead of doing it out of band like that via a `tag(...)` call as that could incur a data race where an entry gets inserted, then the tag gets cleared by another thread, then the tag gets added to the entry after the clear.  It needs to be done atomically at the time the entry is put in.

**Comment by coladarci** [comment]
Right, so the challenge there is that you might not know how to tag something until you've inspected the response from the cache (like in my example; I wouldn't know person's company id until after I pulled the person).. I'm new to cachex, but it feels like the thread issue you raised is related to what the transaction blocks are meant to solve? (https://github.com/whitfin/cachex/blob/master/docs/features/action-blocks.md#transaction-blocks)

**Comment by OvermindDL1** [comment]
Actually I use the fallback handlers exclusively, inside it seems the place to do it there, instead of `{:commit, value}` you could optionally return `{:commit, value, [tag1, tag2, ...]}`.

As for external function that put 'into' the cache rather an a fallback function, should be able to pass it on its parameter list regardless.

**Comment by whitfin** [comment]
@coladarci sorry I only just came to this, but I'm intrigued.

I assume because I took so long, you already figured out a workaround. I was going to suggest just using a secondary cache which is essentially just a tag -> keys mapping (assuming I understood your use case at a glance). Is there still interest in changing Cachex here; is there a need for something built-in?

**Comment by coladarci** [comment]
Truthfully we haven't, yet, found a solution to this. Invalidation is actually a bigger problem for us because we are in a clustered env but we can't use the shared cached as described in the readme because at bootup we don't know all the nodes in the cluster. 

For this reason, any invalidation we do would be per node, which is... useless. 

The way we "solved" this was to use Redis to have a cache key prefix and that allows us to quickly, globally, clear the entire cache. This is obviously useless for invalidating specific records.

**Comment by whitfin** [comment]
Yeah, there's an existing request to improve that so you can dynamically attach nodes _after_ startup, but that's a bit beyond me at the moment (I'm trying to keep a fine line between Cachex and distributed database style logic).

I'm going to close this for now... I think. I think in a world where people need this and have a viable environment to do it in, they can use a secondary mapping table to map their tags to records to remove. To expand on this a little, for reference, you would have a separate cache where you fetch a "tag" and that gives you a list of keys to invalidate from your main cache. This would already work in a distributed fashion... I think.

If this comes up again I'm not against putting it directly into Cachex itself, however the implementation would likely be identical (unless there's some inconsistency I'm missing). In general though, don't be afraid of extra caches used purely for management purposes!

**Comment by coladarci** [comment]
Yeah I completely agree w/ wanting to stay away from clustering if at all possible, that said, I am realizing more and more that this library is a "so close, so far" for me; even w/ my current setup, if we have 4 nodes running you will get a different result very time you load the page because each node will have a separate expiration. This will likely come back as a fire for me and I'm not entirely sure what we'll do about it. 

I assume using something like Redis for the shared cache is no simple ask as an option? We are only caching simple JSON in our example.

**Comment by OvermindDL1** [comment]
> I assume using something like Redis for the shared cache is no simple ask as an option?

Actually doesn't Cachex support different backend providers?  I could imagine a postgresql/redis/etc... one being available as well, but honestly at that point I'd probably just use fallback handlers to load from those and make the local cachex cache even a shorter timeout.
