### ISSUE TITLE
Disabling Cachex in testing env

### ISSUE THREAD

**Issue by jakub-gonet** [whitfin/cachex#229]
Do we have any option to disable caching via Cachex when running tests? I tried setting `size: 0`, but it didn't work, so I settled on `size: 1` and `reclaim: 1` but we still have failing tests in our project. 

Is there any 'official' option for that? If not I'll gladly help implement that

**Comment by whitfin** [comment]
@jakub-gonet nothing built in. I would suggest just purging the cache in a `setup` block, or manually purging when needed. Having something built in seems like we wouldn't have enough information to cover all use cases, and potential to snowball into a bunch of test code.

**Comment by hoangbits** [comment]
using System.get_env("FLAG_TO_INDICATE_TEST_ENV") with conditional helped me out.
