### ISSUE TITLE
Transactions are sharing a lock even when using different keys

### ISSUE THREAD

**Issue by indrekj** [whitfin/cachex#236]
I thought that if you have two transactions with different keys:
* `Cachex.transaction(cache, [ "key1" ], fn(state) ->`
* `Cachex.transaction(cache, [ "key2" ], fn(state) ->`

then these can run in parallel. In reality this is not the case.

Here's a failing test for `Cachex.Actions.TransactionTest`:

```
  test "transactions are independent by key" do
    # create a test cache
    cache = Helper.create_cache([ transactional: true ])

    # spawn a transaction to increment a key
    spawn(fn ->
      Cachex.transaction(cache, [ "key" ], fn(state) ->
        :timer.sleep(50)
        Cachex.incr(state, "key")
      end)
    end)

    # wait for the spawns to happen
    :timer.sleep(10)

    duration_with_result = :timer.tc(fn ->
      Cachex.transaction(cache, [ "other-key" ], fn(state) ->
        assert {:ok, 1} = Cachex.incr(cache, "other-key")
      end)
    end)
    duration_in_millis = duration_with_result |> elem(0) |> Kernel./(1_000)

    assert duration_in_millis < 10
  end
```

Result:
```
  1) test transactions are independent by key (Cachex.Actions.TransactionTest)
     test/cachex/actions/transaction_test.exs:33
     Assertion with < failed
     code:  assert duration_in_millis < 10
     left:  41.257
     right: 10
```

Maybe I'm misunderstanding this and this is actually the expected behavior. In that case do you have recommendations how to have per key transactions?

**Comment by whitfin** [comment]
Hi @indrekj!

It's deliberately undefined. It could be in parallel, or it might not be. In the current implementation, it's a single transaction GenServer, so each one is in sequence. There's some magic we could do in future to make it parallel, but there's a fair amount of extra overhead in the usual case there, so it hasn't been done yet.

Is this something you really need, or did you just happen to notice it?

**Comment by indrekj** [comment]
We do need this but we found a workaround for now: we create multiple cachex workers and partition between them using `phash2(key)`.

**Comment by whitfin** [comment]
I'm going to close this for now because it's intended, and you have a workaround for your use case. If someone comes here in future, maybe we can consider changing it - but it's complex so I don't want to do it lightly.

**Comment by turmeric-blend** [comment]
It would be nice if separate keys had separate lock processes for `transaction`. This block is slowing down my application's processing.
