### ISSUE TITLE
OOM due to Cachex.Policy.LRW not being able to process messages in time

### ISSUE THREAD

**Issue by ananthakumaran** [whitfin/cachex#240]
We have been running cachex in production for some time now and yesterday we got an issue due to cache flooding. We run cachex with a limit of 200 and each item might be in the range of 500kb to 1mb in size. Our application started to crash repeatedly due to OOM. After some investigation we figured Cachex.Policy.LRW process message queue was growing without bound.

I was able to reproduce the issue locally with the following script. Even though the cache size stays under 300, Cachex.Policy.LRW process is not able to keep up with the incoming hook messages and starts to leak memory. This effectively means the throughput is limited by a single process and worse because the eviction is async there is no backpressure applied on the callers side and eventually leads to OOM.

```elixir
defmodule CachexSlow.Workload do
  def run(concurrency \\ 70) do
    import Cachex.Spec

    Cachex.start_link(
      __MODULE__,
      expiration:
        expiration(
          default: :timer.minutes(60),
          interval: :timer.seconds(30),
          lazy: true
        ),
      limit: 200
    )

    1..10_000
    |> Task.async_stream(
      fn _ ->
        key = Enum.random(1..10000)

        _ =
          Cachex.transaction!(__MODULE__, [key], fn state ->
            Cachex.fetch!(
              state,
              key,
              fn _ ->
                # simulate fetch from redis
                Process.sleep(10)
                {:commit, {:ok, :crypto.strong_rand_bytes(1024 * 500)}}
              end
            )
          end)

        IO.inspect(Cachex.size!(__MODULE__))
        :ok
      end,
      max_concurrency: concurrency
    )
    |> Stream.run()
  end
end
```

**Comment by ananthakumaran** [comment]
I tried to convert the eviction from async to sync and it seems to solve the memory issue. I had to inline the `Cachex.purge!()`, otherwise it leads to a deadlock.

```elixir
  def async?, do: false

  defp calculate_poffset(reclaim_space, cache(name: name)) when reclaim_space > 0 do
    count = :ets.select_delete(name, Cachex.Query.expired(true))
    reclaim_space - count
  end
```

is it possible to provide this as an option? so those who prefer memory safety at the expense of speed can select this option?

**Comment by fpalluel** [comment]
Hello, 
I was investigating on OOM in a test app and it seems I'm facing the exact same issue as yours.
The fix you propose is working in my case too, thanks !

**Comment by whitfin** [comment]
I cannot reproduce this, but it's because you are using transactions (many of them) at the same time. This is more a logic issue rather than a bug in the LRW policy, because it uses transactions too. You're blocking up the transactions message box. I'd be interested if you actually need transactions, and what your real use case is that's causing this to happen?

**Comment by ananthakumaran** [comment]
Not sure if anything has changed since I opened the issue, I was able to reproduce it easily with the above script. The memory growth could be observed using observer.

As for the usage of transactions, we want to make sure the fallback function doesn't get called concurrently for the same key. Some of the resources are costly to compute and we don't want to create unnecessary load. Support for transactions was one of the main reasons we used cachex.

**Comment by whitfin** [comment]
I couldn't get it to happen, but I'll check again in case I missed anything.

> As for the usage of transactions, we want to make sure the fallback function doesn't get called concurrently for the same key.

This is automatically handled for you; if two calls happen for the same key, the first one will do the fetch and the second call will just await the result of the first one. You shouldn't have to do it in a transaction; if you see behaviour differently to this, there's a bug somewhere.

**Comment by ananthakumaran** [comment]
> I'm fairly sure this is issue is just a result of using transaction in places they shouldn't be used

Probably. The issue itself happened under very high load and in one specific instance. As I mentioned initially, we had been using it for years without any issue. Unfortunately, I didn't get much time to dig deeper, as we solved the problem by using a different library, I lost the motivation to look further into the issue. It makes sense to close the issue.
