### ISSUE TITLE
Question about default Janitor and ttl behavior

### ISSUE THREAD

**Issue by shayne-lp** [whitfin/cachex#243]
Hello,

I am using the default Cachex settings, with a cache size (`limit`) of 5,000 elements, for a nightly job that does lookups on several thousand keys in an external service. I would like to allow those elements to remain in the cache (indefinitely, really), and only when the 5k limit is reached start replacing them in an LRU manner, so as to reduce the external service lookup frequency.

Use case 1: It runs for weeks, never having more than 5k cache entries, so it should always have a cache hit on `Cachex.get`.

Use case 2: The nightly job starts pulling 15k entries, but most are not read (`Cachex.get`) frequently, so it would expire the least recently "gotten" to stay within the 5k limit on any `Cachex.put`.

Can anyone shed any light on if this configuration is supported by Cachex?

Thanks!

**Comment by OvermindDL1** [comment]
Sounds like one of the cases I use it for, just don't use TTL and have a size eviction.  Did you have issues setting it up?

**Comment by shayne-lp** [comment]
I must have missed the size-based eviction option. Mind sharing a sample config snippet you used? Thanks @OvermindDL1!

**Comment by OvermindDL1** [comment]
Here's the limit option from one of my projects that I'm using:
```elixir
      limit: limit([
        size: 1000, # Raw values kept
        policy: Cachex.Policy.LRW, # The only built-in policy, Least-Recently-Written
        reclaim: 0.1, # The % from 0.0 to 1.0 to delete when limit is exceeded, with a limit of 500 and reclaim of 0.1 then 50 will be purged at time
        options: [],
      ]),
```

**Comment by OvermindDL1** [comment]
It defaults to `nil` for the `:size` key:
https://github.com/whitfin/cachex/blob/v3.2.0/lib/cachex/spec.ex#L228

**Comment by shayne-lp** [comment]
This is super helpful, thanks @OvermindDL1. And just to confirm your goal, by not setting any `ttl` on a `put`, the cache will stay populated with all prior entries and will not start evicting until the size is exceeded? This is great, thanks!

**Comment by OvermindDL1** [comment]
Yep yep.  :-)

**Comment by shayne-lp** [comment]
Thanks!!
