### ISSUE TITLE
CachexHooks don't receive information when items exceed TTL

### ISSUE THREAD

**Issue by stwf** [whitfin/cachex#249]
In my setup I'd like to use Cachex's TTL functions.

But I need to know which items get purged. When I manually delete a key the Hook receives the info as to which key is deleted, but items purged via TTL do not. 

I just see
```
Message: {:purge, [[local: true]]}
Results: {:ok, 1}
```
to let me know something was deleted. Getting the key here would be a great addition.

Thanks

**Comment by whitfin** [comment]
This it not possible for a couple of reasons:

* You could have thousands of keys - broadcasting this is expensive.
* Purge is optimized inside the underlying ETS table, so we don't actually know which keys were removed - fetching them out is also very expensive and turns a single operation into multiple.

I'm curious what your use case is, maybe there's an alternative
