### ISSUE TITLE
Incorrect spec for Cachex.expire_at/4

### ISSUE THREAD

**Issue by ischepin** [whitfin/cachex#256]
Hello, I noticed that function `Cachex.expire_at/4` has incorrect spec:
```elixir
@spec expire_at(cache(), binary(), number(), Keyword.t()) ::
          {status(), boolean()}
def expire_at(cache, key, timestamp, options \\ [])
```
`key` should be any, as in other `Cachex` functions.

**Comment by whitfin** [comment]
Thanks! Fixed in https://github.com/whitfin/cachex/commit/dea5f9930e635b2d22329c05f9c563754fa77670.
