### ISSUE TITLE
[Proposal] Add put_and_get function

### ISSUE THREAD

**Issue by Koziolek** [whitfin/cachex#258]
Let's add `put_and_get` function to mail API of Cachex. 

### How it should work

Function `put_and_get` should work similar to `put`, but return additional element – value:

```elixir
iex > Cachex.put_and_get(:my_cache, "key", "value")
{:ok, true, "value"} 
iex >
````

### Motivation

In some use cases we use flow like:

```elixir

def do_something(key) do

{_, value} = Cachex.get(:my_cache, key)

  case value do
     nil -> 
          new_value = some_heavy_computation(key)
          Cachex.put(:my_cache, key, new_value)
          new_value # the important line
    _ -> value
  end

end
```
Now if you omit _the important line_, then you get `nil` on return from `do_something`. This change is ‘quality of life‘ change, that protect developers against some type of errors. 

### Impact to existing API

[Nope](https://lh4.googleusercontent.com/proxy/scZNybh8JxEKbFn8O9yDLQmmMQ9qbBpMeBYHGI0fa0mYQwPfSgCZ_H5NDkU-bkw7iBZ_QYUJaXi65zvX_7icEpGALmwUicblPpFCqamBhGqp5KYp_as-K8ECjTKkOYPj)

**Comment by whitfin** [comment]
This is already covered by using `get_and_update/4`. Please see the examples in the docs: https://hexdocs.pm/cachex/Cachex.html#get_and_update/4

**Comment by conradfr** [comment]
I think `fetch/4` does what you need.
