### ISSUE TITLE
Time based test are unstable

### ISSUE THREAD

**Issue by Koziolek** [whitfin/cachex#260]
Test based on time are unstable. Example:

https://ci.appveyor.com/project/whitfin/cachex/builds/35936438
https://ci.appveyor.com/project/whitfin/cachex/builds/35936757 

and, of course, cannot reproduce on localhost.

### Possible solutions

* Convert some test to benchmark 
* Change test conditions and/or add information in documentation

**Comment by whitfin** [comment]
Hi! 

This was definitely unstable, largely in part to AppVeyor being extremely inconsistent with performance within builds. Now that we're not using AppVeyor anymore, we shouldn't see this going forward so I'm going to close this.

If we do see this again, I can re-open this and we can consider changes. Thank you!
