### ISSUE TITLE
Does Cachex.transaction take time for the first call?

### ISSUE THREAD

**Issue by anildigital** [whitfin/cachex#271]
In an application, there is a following call

```elixir
Cachex.transaction(@cache, cachey_keys, fn foo ->
  # loop to get values from cache
  Cachex.get(foo, key)
  . . .
end
```

When benchmarked, I noticed that above takes 2000+ microseconds on first call. But on second call it takes around 130 microseconds.

I noticed performance of `Cachex.get(foo, key)` is consistent. But it seems that `Cachex.transaction(` takes more time on first call.

Could this be true considering Cachex design? Thanks!

**Comment by whitfin** [comment]
It's very hard to comment on this without seeing your benchmarking code. In general, no, the first call should be no slower than any other, but it depends.
