### ISSUE TITLE
Support callback for removed data from policy

### ISSUE THREAD

**Issue by sezaru** [whitfin/cachex#272]
Hello, looking at the `Cachex.Policy` callbacks and at the LRW implementation, it seems that there is no support for a callback for each removed data from the cache.

Is this something that can be considered or do you think it is too much out-of-scope?

To make it a bit clear what I want to achieve, I will describe my current architecture:

Basically, my cache consists of a cache of ETS tables, I have a GenServer called `EtsHolder` which is the owner of these tables, when a new key is added to the cache (via `Cachex.fetch!`), it calls `EtsHolder` to create a new table and then stores that table inside the cache.

What I want to achieve now is to have some policy to keep the cache size under control, to do that the `Cachex.Policy.LRW` seems like a good candidate. But the issue is that using LRW I simply don't know what, when and if a table was removed from the cache, so I can remove it from `EtsHolder` too and completely remove it from memory.

What I propose is to have an optional callback that is [above this line](https://github.com/whitfin/cachex/blob/ff93af887615a896f5838262c019c3cb37d1f28b/lib/cachex/policy/lrw.ex#L231) which will send the table reference with the key to some function that the user can use to do some other work with it (in my case, identify which data is being removed and call the delete function from `EtsHolder` too).

I can easily simply get your LRW implementation and change it for my needs, but I was wondering if you think this is a good addition to the library itself or if you have a better idea to handle this.

**Comment by whitfin** [comment]
There are a couple of reasons why this is a pain (and why it hasn't been done):

* The general case of a cache will have hundreds or thousands of keys being removed at once, leading to a very slow handling if you fire a function on every key.
* The way Cachex works is using a hook system; there's really no way to have a hook fire another hook (it's a flattened system). So this would require special handling, but based on the point above... I don't think it's worth it.

If you have suggested changes I can take a look at them; but please benchmark against caches with several hundred keys being removed at once etc.

**Comment by sezaru** [comment]
That's fair, I think the best way is to me simply reimplement the LRW for my needs since it is kinda niche, I guess that's why you provide the `Cachex.Policy` callbacks ;)
