### ISSUE TITLE
Cachex (-> Sleeplocks) not working on Elixir 1.12.1

### ISSUE THREAD

**Issue by fr4nz909** [whitfin/cachex#274]
When updated Elixir to the newest version 1.12.1, sleeplocks gives the error that some functions inside rebar3 can’t be found and thereby sleeplocks dependency can’t compile. As Cachex is a dependent of sleeplocks, Cachex also won’t work.

**Comment by whitfin** [comment]
I am unable to reproduce this; do you have `rebar3` installed? 

Can you provide details on how to reproduce? On a fresh install of `1.12.1` in a fresh clone, everything compiles correctly.

**Comment by sezaru** [comment]
I can reproduce this in some scenarios, specially inside my docker image that I use for deployment.

If you want, you can try to reproduce using it, you can find it in this forum post I created about the issue: https://elixirforum.com/t/release-build-failing-with-undefined-function-erlang-get-stacktrace-0-after-otp-24-update/40274

**Comment by whitfin** [comment]
Looking at that post, it's environmental or something to do with `rebar3` rather than the `sleeplocks` package itself. 

Also it appears this is an OTP 24 thing, rather than an Elixir v1.12.1 thing?

**Comment by sezaru** [comment]
It seems probable more like a `rebar3` thing, I searched their GitHub issue and there are issues about this, for example:
https://github.com/hexpm/hex_core/pull/106
https://github.com/erlang/rebar3/pull/1773
https://github.com/erlang/rebar3/pull/2361
https://github.com/erlang/rebar3/pull/2515

But they all are already closed or merged issues, so I'm not sure why this is triggering now, to be honest.

**Comment by whitfin** [comment]
I'm *fairly* sure this is just a `rebar3` incompatibility and there's nothing to be done about it on library sides of things. I would assume that the `rebar3` version installed by `mix` needs to be updated. 

Not entirely sure if I should close this or not but I can leave it open for now.

**Comment by sezaru** [comment]
I was able to fix it by changing my `HEX_MIRROR` for some reason...

What I did was:
```bash
HEX_MIRROR=https://cdn.jsdelivr.net/hex mix local.hex
HEX_MIRROR=https://cdn.jsdelivr.net/hex mix local.rebar
```

**Comment by sezaru** [comment]
@whitfin the issue was a hex serve regression, José Valim already fixed it here https://github.com/elixir-lang/elixir/issues/11047#event-4850239059 :D

I think you can close this issue.

**Comment by fr4nz909** [comment]
Thanks for the many responses guys! :)

I also fixed it in the meantime with something like @sezaru did. :D
