### ISSUE TITLE
Best practice for "infinite TTL"?

### ISSUE THREAD

**Issue by thbar** [whitfin/cachex#275]
Thanks for this great library!

In a number of cases, we use Cachex (amongst other scenarios) to cache a remote HTTP config. Its lifetime is "infinite" (until the moment we discard it, in which case we reload it).

Currently I'm using a `:timer.hours(100_000)` ttl so that it lasts almost forever (and an expiry is not a problem).

Is there a better way to achieve this with Cachex? Thanks!

**Comment by whitfin** [comment]
The expiration behaviour of Cachex is entirely optional; you can just place into the cache with no TTL option set and the key will never be expired: https://github.com/whitfin/cachex/blob/master/lib/cachex.ex#L1008-L1009

**Comment by thbar** [comment]
Very nice, thanks for the explanation. Thanks, I'll close the issue!
