### ISSUE TITLE
Dialyzer warning in Warmer module

### ISSUE THREAD

**Issue by chazsconi** [whitfin/cachex#276]
There is a dialyzer warning on the `init/1` function generated by the `Warmer.__using__` macro.

With this sample client code:
```
defmodule CachexTest do
  use Cachex.Warmer

  def interval, do: 0
  def execute(_), do: :ignore
end
```

`mix dialyzer`  gives:

```
lib/cachex/warmer.ex:72:guard_fail
The guard clause:

when _ :: {:noreply, {_, _}} === nil

can never succeed.
```

I believe this is because in the `init` function https://github.com/whitfin/cachex/blob/master/lib/cachex/warmer.ex#L72
the call to `handle_info/2` will always return a non-null value, and hence the `&&` serves no purpose.

The fix would be just to change it to:
```
      def init(state) do
        handle_info(:cachex_warmer, state)
        {:ok, state}
      end
```

I'm happy to provide a PR for this if required.

**Comment by whitfin** [comment]
https://github.com/whitfin/cachex/commit/a0ef5788859b340831bd4b491464f9ce34fdb1dc <3

**Comment by seungjinRonin** [comment]
Any chance knowing when this will be released? I'm seeing this issue too
