### ISSUE TITLE
Cachex Warmers Issue with 3.4.0 Elixir 1.12.3 and OTP 24.0.6

### ISSUE THREAD

**Issue by vasumur** [whitfin/cachex#279]
Hi

Appreciate if you could look into this.  Currently application is working in Elixir 1.10.4 and OTP 23.1 and I am in the process of upgrading it to Elixir 1.12.3 and OTP 24.0.6.

After further research I am able to narrow down to the below pattern why the warmers are failing to start.

During application startup

If the proactive cachex warmers when they initialize is calling another cachex entry which is going to be proactively loaded using Cachex.fetch/3 routine is failing.

I don't have this issue while running in 1.10 and I am using cachex 3.2.0 version.

Please let me know if any additional information is required to look into this, this is blocking me from migrating to latest Elixir version.

Thanks

**Comment by vasumur** [comment]
@whitfin 

Appreciate if you could look into this issue, By downgrading to 3.2.0 version, this one is working.

**Comment by whitfin** [comment]
Can you please use the latest Cachex version on the latest version of Elixir/OTP, and then 3.2.0 of Cachex on the latest version of Elixir/OTP? 

I want to make sure it is a Cachex *bug* rather than some new Elixir compatibility issue.

**Comment by vasumur** [comment]
@whitfin 

Yes I tried that. Here is the summary of what I tried, happy to provide additional details.

In both the attempts I am using the following config.
elixir 1.12.3-otp-24
erlang 24.0.6

With Cachex 3.2.0 version, the cachex are warmed in parallel and any proactive warming if it calls reactive cache warming calls, they don't fail with {:error, :no_cache} error


With Cachex 3.4.0, the warms are running sequentially and also throwing error if I get into the situation where the proactive warmer is calling the reactive ones  (Cachex.fetch(cache_name, key, fallback_fn) calls).

Two things I noticed with 3.4.0 is the cache warming is completely sequential and also this cachex.fetch call fails if it is called during the warming phase.

**Comment by vasumur** [comment]
Also is this the recommended way to start multiple cachex warmers. I am trying to get rid of the warnings about the worker being defunct.

Just so we are on the same page, I did use the worker approach while testing with 3.2 and 3.4.

Thanks for your help

Muralee


      Supervisor.child_spec(
        {Cachex,
         [
           name: :users,
           warmers: []
         ]},
        id: :users
      ),
      Supervisor.child_spec(
        {Cachex,
         [
           name: :common,
           limit: 9999,
           warmers:
             case Application.get_env(:tradeserf, :env) do
               :test ->
                 []

               _ ->
                 [
                   warmer(module: Tradeserf.Warmers.PbdCbdWarmer, state: nil),
                   warmer(module: Tradeserf.Warmers.EntityAddlAttributesWarmer, state: nil),
                   warmer(module: Tradeserf.Warmers.AnalyticCodesWarmer, state: nil),
                   warmer(module: Tradeserf.Warmers.StrategyWarmer, state: nil),
                   warmer(module: Tradeserf.Warmers.BetaCodesWarmer, state: nil),
                   warmer(module: Tradeserf.Warmers.GroupingLevelCodesWarmer, state: nil),
                   warmer(module: Tradeserf.Warmers.NewIssuesWarmer, state: nil),
                   warmer(module: Tradeserf.Warmers.CrdExchangeRatesWarmer, state: nil),
                   warmer(module: Tradeserf.Warmers.LotHoldingsRefCodesWarmer, state: nil),
                   warmer(module: Tradeserf.Warmers.SizetoMajorMinorCodesWarmer, state: nil),
                   warmer(module: Tradeserf.Warmers.IoUsersGroupsWarmer, state: nil),
                   warmer(module: Tradeserf.Warmers.DatasetLoadStatusWarmer, state: nil),
                   warmer(module: Tradeserf.Warmers.ProfileBasedDataWarmer, state: nil)
                 ]
             end
         ]},
        id: :common
      ),****

**Comment by whitfin** [comment]
Does the issue also happen on the 3.3.x versions? Or just 3.4? If possible, this would be much easier to debug with a reproduction case. 

It sounds like there are a lot of caches working together in your case; if you could come up with a small example that I can use to reproduce I can look at it!

**Comment by vasumur** [comment]
@whitfin 

Seeing similar issue in 3.3.0 as well. I am going to attempt putting together a small application to simulate that.

But one thing I noticed that when I upgraded from version 3.2.0 is that the warming is happening as a sequential step whereas it was not the case with 3.2.0 version.

**Comment by whitfin** [comment]
This will be related to https://github.com/whitfin/cachex/pull/244 but I'm unsure whether or not it's because of a strange usage pattern or if we need to change something in Cachex for your use case.

**Comment by vasumur** [comment]
@whitfin

I have put in a toned down version in the repository below.

https://github.com/vasumur/cachex_test

This was tested with the below config.

elixir 1.12.3-otp-24
erlang 24.0.6

If you run this in 3.2.0, the cachex warmers for both cache common and security would run fine without any issues.

If I tried the same thing with 3.4.0 cachex version

[error] Error While Warming data - %MatchError{term: {:error, :no_cache}}
[error] ** (MatchError) no match of right hand side value: {:error, :no_cache}
(cachex_test 0.1.0) lib/cachex_test/util.ex:243: CachexTest.Util.load_security_data_into_cache/1
(cachex_test 0.1.0) lib/cachex_test/util.ex:236: CachexTest.Util.fetch_data/1
(cachex_test 0.1.0) lib/cachex_test/warmers/data_warmer.ex:16: CachexTest.Warmers.DataWarmer.execute/1
(cachex_test 0.1.0) lib/cachex/warmer.ex:84: CachexTest.Warmers.DataWarmer.handle_info/2
(cachex_test 0.1.0) lib/cachex/warmer.ex:72: CachexTest.Warmers.DataWarmer.init/1
(stdlib 3.15.2) gen_server.erl:423: :gen_server.init_it/2
(stdlib 3.15.2) gen_server.erl:390: :gen_server.init_it/6
(stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

Based on what I understand from the logs is that the warmers are running sequential in 3.4 and that is why the security cache is not even available while the "common" cache warmer loads the data into the security.

My question is, is there a way create the caches first and then attach warmers to them. Even if we have to run them sequentially is fine as well.

**Comment by whitfin** [comment]
@vasumur the reason you're hitting this is that you're using a cache warmer to lookup inside the same cache the warmer is for; the logical thing to do here is to have two separate cache tables rather than one table you put everything inside.

If you had a `:pdb_cache` and a `:data_cache` instead of a single cache named `:common`, this problem them goes away - and there's no impact to your application.

**Comment by vasumur** [comment]
@whitfin 
Yes, totally agree with that. The changes between the 3.2.0 and above I wanted to highlight are below.

1. Multiple caches in Cachex are created in sequential order, this is not the behaviour in 3.2.0. In the above case in 3.2.0, both pbd_cache and data_cache would have been created, and then the warmers kick off in parallel
2. Since warmers are executing in sequential way by default, is there an option to have the old 3.2.0 behaviour back? I understand we can group the routines and run them in parallel. But in cases where they have different intervals.

**Comment by whitfin** [comment]
Yes, the change in v3.2.0 is intentional due to a bug; the parallel warmers created behaviour where you couldn't guarantee that you would have the same results consistently. Having warmers be blocking guarantees this, even if you do have to restructure a little. So it's unlikely an option will be added to remove this.

I'm not sure I understand the question you're asking; you start a cache like [this](https://github.com/whitfin/cachex#usage). If you need multiple caches, you just add multiple entries to this list for the other caches, right?
