### ISSUE TITLE
Can the expire function return an :error ?

### ISSUE THREAD

**Issue by fchabouis** [whitfin/cachex#281]
Hello,
Following https://github.com/whitfin/cachex/issues/195 discussion, I understand that a good practice when using `fetch` is to first call `fetch`, and then set a TTL if needed using `expire`.
We have recently had some problems with cache entries without TTL, and for the moment we don't understand how it's possible, as we call `expire` after a cache `:commit` is made.
However, I note that `expire` returns `{:ok, true}` when successful. Is there any chance the call could _for some reason_ return an `{:error, _}`?
That could explain why we sometimes have a cache entry without any TTL set.

**Comment by whitfin** [comment]
Do you have a reproduction case? No, there should not be an `:error` for `expire` outside of the usual errors such as no cache existing, etc.

**Comment by fchabouis** [comment]
Thanks. We'll continue to investigate this, for the moment it happens a couple of times a day, out of thousands of calls. We have set up a GenServer that watches for cache entries, clean any keys without the proper TTL set, and send a message in Sentry. But we would like to understand what is going on.

**Comment by whitfin** [comment]
@fchabouis did you find any further information about this? Otherwise I'm going to close this for the time being; but feel free to comment if you have more info or need more help!

**Comment by fchabouis** [comment]
We have no additionnal information. Some ttl are not set and we don't know why for the moment. Thanks for  your time.
