### ISSUE TITLE
The `:ttl` option is not supported by the `fetch` function

### ISSUE THREAD

**Issue by TylerPachal** [whitfin/cachex#282]
It looks like the `Cachex.fetch` function does not support the `:ttl` option like the `put` function does.  The `fetch` function is very handy for creating a read-through cache, but would be more useful if I could set the fallback-given values to expire.

I created a test to prove that it is not currently supported:

```
test "inserting values via the fallback function supports ttl" do
  cache = Helper.create_cache()

  # insert a value via the fallback function
  result = Cachex.fetch(cache, "key", &String.reverse/1, ttl: 5)

  # confirm value is present
  assert {:ok, "yek"} == Cachex.get(cache, "key")

  # wait for ttl to expire
  :timer.sleep(10)

  # confirm value is no longer present
  assert {:ok, nil} == Cachex.get(cache, "key") # <-------------------- fails here
end
```

**Comment by whitfin** [comment]
Hi @TylerPachal! Thanks for the PR/issue but unfortunately I will be closing this as this has been discussed in the past and has not been added deliberately. For the existing discussions please see https://github.com/whitfin/cachex/issues/177 and https://github.com/whitfin/cachex/issues/195. 

If you need any clarifications, please do let me know!
