### ISSUE TITLE
Issue with specific cache key

### ISSUE THREAD

**Issue by dbhaasis** [whitfin/cachex#287]
Ran into weird issue where a specific cache key seems to be getting in infinite loop or something. The cache (:resolver_cache) was set up with a short cache time of 1 second as only used to prevent multiple calls in same graphql request in absinthe.

Here is call that would never return.
`Cachex.fetch(:resolver_cache, {:season_tags, 1707, 23702601}, fn {_,_,_} -> "something" end)`

Changing any of the 3 values would make the call work as expected, but this combination of :season_tags and the 2 numbers caused the request to get stuck. We changed to use a string instead of atom for the sub area of the cache to make it work, but seems strange that the combination of values caused `fetch` to hang. 

****** 

UPDATE: So it seems to be an issue with the cache getting into a weird state and a specific key causing the issue. As this issue has happened several times. When in this state, clearing the cache does not fix the issue. Restarting the app does fix the issue. I'm guessing somehow the key is getting stored somewhere that doesn't actually show up as being in the cache and is in an invalid state which causes the fetch to hang.

**Comment by whitfin** [comment]
@dbhaasis are you able to provide a reproduction case for this? If you run this in an empty project, does it still happen?

**Comment by dbhaasis** [comment]
I don’t think it is easy to reproduce and it is likely a rare occurrence. It has only happened to data that is hit by automated tests. My only guess is a some type of timing issue if key is inserted at same time. It hasn’t happened for a while and the tests run every day. 

David Haasis

**Comment by whitfin** [comment]
Calls to `fetch/4` will routinely hang as they're queued up through another service and executed in the background. I can only assume that somehow your fetching function either crashed or just didn't return.

Were you doing anything specifically complicated inside your fetch function? Obviously `"something"` is just a placeholder, right?

It makes sense to be something with the fetching service, as clearing the cache would not clear the state of fetches flowing through that service.

**Comment by whitfin** [comment]
I'm going to close this for now but feel free to follow up with a reproduction case or more information if you have any, and I can look again!

**Comment by whitfin** [comment]
It looks (tentatively) like this has been reproduced as a legitimate issue, so further discussion and work on this will happen in #319 where we're trying to work on a reproduction case!
