### ISSUE TITLE
Add a very basic LRU cache clear implementation

### ISSUE THREAD

**Issue by whitfin** [whitfin/cachex#305]
There's a really "easy" way to implement very basic LRU using LRW, by adding a hook to the LRW implementation to update touch time when a key is accessed and then using LRW as usual. We should add this basic implementation to the repository (and obviously document the changing touch time).

**Comment by whitfin** [comment]
I still don't like including this, because people will see LRU available and gravitate to it naturally. I think maybe putting some docs together, rather than including it, would be a better way to solve this.

**Comment by juancgalvis** [comment]
> I still don't like including this, because people will see LRU available and gravitate to it naturally. I think maybe putting some docs together, rather than including it, would be a better way to solve this.

Hello, @whitfin do you have a recommendation to do a basic LRU policy?

**Comment by whitfin** [comment]
@juancgalvis I am once again going to consider this for v3.7.0 coming soon - no promises, but I'll definitely at least document an example.
