### ISSUE TITLE
Does `Cachex.fetch` accept `ttl` option?

### ISSUE THREAD

**Issue by hissssst** [whitfin/cachex#307]
Could you please improve documentation of `fetch` operation options?

**Comment by whitfin** [comment]
@hissssst no, and it is [already documented](https://github.com/whitfin/cachex/blob/main/docs/features/cache-warming/reactive-warming.md#expirations).

**Comment by hissssst** [comment]
@whitfin than why does this function have options argument?

**Comment by whitfin** [comment]
@hissssst to conform to the standard API of every function in the lib.

**Comment by hissssst** [comment]
This is really strange to be honest. I've never seen an unused argument for options (except for compatibility reason). For me this was misleading ...

Anyway, thanks for the clarification on the original question <з
