### ISSUE TITLE
Sending a message to `self()` when starting a warmer crashes app

### ISSUE THREAD

**Issue by apreifsteck** [whitfin/cachex#314]
While creating a warmer module implementation, I sent a message to `self()`, and found my app crashing on when it was trying to boot. I threw a few inspects in and found that the `execute` function in the warmer implementation was being called again and again, each time with a different pid until it seemed to bring down the app. I tried changing up the message and it made no difference.

**Comment by whitfin** [comment]
Do you have a reproduction case I can look at?

**Comment by apreifsteck** [comment]
Sure, I made [this](https://github.com/apreifsteck/cachex_error_reproducer) basic error reproducer. It looks like the genserver that the warmer gets turned into is not equipped to handle random messages and crashes, then gets restarted, and the loop just repeats. 

To add some more context about why in the heck someone would be sending messages inside the warmer:
At my work we use Cachex to create a readthrough cache by querying some other REST APIs. Pretty normal. The twist is that we will switch out the real HTTP clients for mocks that emit some messages when you call them (with the arguments and so forth that it was called with) so that in a test you can make assertions on these messages. So in test the mock gets used in the warmer and sends a message using `self()` and then _boom_.

**Comment by whitfin** [comment]
@apreifsteck okay, I get it :) thank you!

I'm a bit mixed on this, because I don't want to blindly add a catch-all for messages (it's pretty easy to introduce bugs this way). Especially for something like this: why would I make something "worse" for mocks? Although I personally dislike mocking so I might be a little biased here.

I'm assuming there's no way to stop the mocks sending to `self()`? Is this using a common mocking lib? Basically... is this that's specific for you, or is this e.g. some popular mocking lib where this change would help many people? 

I might just add a catch anyway, maybe I'll just log it as something unknown or something (I plan on adding some logging later, if I can avoid overhead).

**Comment by apreifsteck** [comment]
> why would I make something "worse" for mocks?

Totally get where you're coming from here. I definitely don't want to ask for any changes that would compromise the usability of the library. It's great 👍 .

> I'm assuming there's no way to stop the mocks sending to self()?

I had rolled the message passing into a macro, but it was a simple one so I just used a stripped down version (with no message passing) for the warmer as a workaround. So no, it's not a mocking library, it's something I had set up.

> I might just add a catch anyway

Up to you! I was noodling on this a bit. I'm assuming the warmers start as a part of a supervision tree of the Cachex application (I haven't actually looked at the architecture). Thinking that way, there really isn't any reason I should be sending messages from within the warmers (at least to `self()`). The trouble is that I didn't know that's what was happening for a while :). Would it be possible to raise an exception with a helpful error message if there's an unexpected (process) message received? That would make it easier to figure out what's happening I think, if anyone encounters this in the future.

**Comment by whitfin** [comment]
@apreifsteck I just realised, you can actually just implement this yourself:

```
defmodule CachexErrorReproducer.WillBreak do
  use Cachex.Warmer

  def interval,
    do: :timer.seconds(30)

  def execute(_) do
    dbg(self())
    send(self(), :wreck_it)
    {:ok, [one: 1]}
  end

  def handle_info(message, state) do
    {:noreply, state}
  end
end
```

You can override and provide a default handler, although this is not documented. This should at least unblock what you need going forward!

I think I'll probably lean to not changing it for now, given that you can always do something like this - maybe I need some docs additions around this. Let me know if this works out in your real use case, and then I'll close out this issue!

**Comment by apreifsteck** [comment]
🤔 Seems like it should work, but I'll let you know for sure when I get back to work in the new year. No matter what though, thanks for taking a look!

**Comment by apreifsteck** [comment]
Thank you for the gentle nudge, @whitfin! Just tested the default handler, and it works great! I'll go ahead and close this out. Thanks again 👍
