### ISSUE TITLE
qlc error - max limit cache eviction fails for no cwd write permissions

### ISSUE THREAD

**Issue by aerosol** [whitfin/cachex#329]
`qlc` uses the filesystem to store cursor information. 

The result of `qlc` calls is discarded by Cachex, therefore it's possible to observe the following error logged - in case the current working directory is not writeable upon cursor/batch erase:

```
{:error, :qlc, {:file_error, ~c"appname-01_1_2222737.1", :eacces}}
```

Resulting with a silent failure of cache eviction.

I think the preferable approach would be to allow overriding qlc's `{tmpdir, TempDirectory}` configuration as per https://www.erlang.org/doc/man/qlc#common-options.

**Comment by whitfin** [comment]
@aerosol sure thing, want to PR it? Happy to include and get a patch out.

**Comment by aerosol** [comment]
> want to PR it? 

Possibly, given enough capacity, will keep you posted.

> So is QLC accepting an error as an input and not logging anything? Or is the comprehension masking the error here? Just want to clarify how it's possible this is failing silently, because at a glance it looks reasonable?

Ah yes, apologies for imprecise wording - it's not completely silent, in the sense a a one-off mismatch error happens in `Cachex.Policy.LRW.erase_batch/3`. Not much else besides that - the cache keeps happily growing over the limit.

![image](https://github.com/whitfin/cachex/assets/173738/124a0b19-8c2c-4720-a869-75f9901161b6)

> Edit: note to self and future readers that this affects the cache max limit eviction, not general eviction.

Thanks, I'll update the ticket title.

**Comment by whitfin** [comment]
Awesome, thank you for the clarification - no worries if you're too busy to PR it, I can probably carve out some time tonight for this.

I've been trying to get a reproduction case but it's a little awkward, I guess I have to pre-package an app with Cachex to test it. I haven't yet been able to make the `tmpdir` option do anything (or at least visibly do anything).
