### ISSUE TITLE
Write through layered caches

### ISSUE THREAD

**Issue by tlvenn** [whitfin/cachex#99]
Right now, Cachex features read through caches with the use of the fallback method. It would be great if in the same fashion, we could get write through caches as well. I guess by leveraging the hooks, one could already do that but I am wondering if we could not make it simpler, more obvious.

**Comment by zackehh** [comment]
Hi @tlvenn!

I'm not sure I see the value of write-through. It introduces a lot of overhead into Cachex in places where people will rarely need.

I'm interested in what you think of this though, and if it fits what you want (this is typically what I do if I need the same behaviour). I'm going to use Redis as an example of the outer layer.

- Direct all your writes directly to Redis
- Direct all your reads to Cachex with a Redis fallback
- Optionally, make your Redis write calls evict the local Cachex entry

This is has the same effect, as your writes hit Redis and your caches always reflect the latest reads from Redis. The only difference is that your cache will wait to populate with the new write until it's asked for (which is arguably better).

Does this seem sufficient, or is there still something you see missing here? Or do you have a specific concern?

Let me know!

**Comment by tlvenn** [comment]
Hi @zackehh,

For me the value of a layered cache is to hide some complexity of those layers or that those layers even exist to some extent. From an api point of view, I want cachex to be my single point of contact.

I should be able to change the configuration of a given cache to:

- only use ETS, no layered cache
- ETS + disk
- ETS + redis
- ETS + XXX

And it would not impact my code at all because cachex is my only interface and it handles transparently for me to read and write from the layered caches. To my knowledge, this is how most layered cache works.

If we were to introduce a `secondary_cache` behaviour, I believe it would be fairly easy to implement a `redis_secondary_cache` with a pluggable client and integrate that behaviour as a config option to a given cache and wire it on the different actions using a hook.

What do you think ?

**Comment by zackehh** [comment]
Hey @tlvenn,

I started writing a response explaining why we shouldn't do this but then thought of a way we might be able to make it plausible. The big issue is a performance hit and tying Cachex code too closely to other projects - e.g. if you define a custom Cachex command called `lpop`, Cachex can't know the Redis equivalent.

I'll think about this a little more and get back to you, no promises though.

**Comment by fire** [comment]
Did you think about this more? I was interested if you had anymore ideas. 

My idea was using this library as a cache and then writing code that syncs the data to ecto asynchronously.

**Comment by whitfin** [comment]
@fire I did, but really there's no way I can think of implementing it without bloating the codebase with knowledge of something like Ecto.

Any ideas?

**Comment by tlvenn** [comment]
ya those secondary cache need to come as plugins in their own lib such as `cachex-redis`, `cachex-ecto` etc.. It should not be in the cachex code base for sure. Cachex should only provide the behaviour that need to be adopted by those plugins.

As for custom commands, maybe this is simply not supported by secondary caches at all, only k/v operations would be supported.

Now i understand this could become a rabbit hole quite quickly and maybe not desirable.

**Comment by fire** [comment]
I moved to https://github.com/cabol/nebulex_ecto , but thank you for the discussion. It uses a library for caching -- nebulex and then an ecto adapter.

**Comment by whitfin** [comment]
I'm going to close this I think, for a number of reasons. Mainly I believe that write-through is actually a less consistent pattern than what can be achieved with fallbacks. What would happen if the Cachex write works and then the write in Redis fails? Boom, you have an issue.

In addition, it's not an easy thing to write in a maintainable way and I can see supporting it being difficult (for something that's of questionable necessity), and as such I'm going to punt it for now. If anyone else can provide additional statements why it should be added, I'm totally willing to reconsider!
